// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 28 Aug 2018 21:43:25 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vk provides Go bindings for vulkan.h
*/
package vk
